name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-package: jdk
        java-version: 8
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Grant execute permission for gradlew
      run: chmod +xrw ./gradlew
    - name: Run Gradle
      run: ./gradlew
    - name: Setup Dev Workspace
      run: ./gradlew setupDevWorkspace
    - name: Setup Decompile Workspace
      run: ./gradlew setupDecompWorkspace
    - name: Setup Eclipse Workspace
      run: ./gradlew eclipse
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/libs
